---
swagger: "2.0"
info:
  description: "cs3733 YAML API"
  version: 1.9.9
  title: "cs3733 YAML API"
host: "65y680psjl.execute-api.us-east-2.amazonaws.com"
basePath: "/beta"
schemes:
- "https"
paths:
  /admin:
    get:
      operationId: "createReport"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/ChoiceInfoList"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:createReport/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    post:
      operationId: "deleteChoices"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "DeleteChoicesRequest"
        required: true
        schema:
          $ref: "#/definitions/DeleteChoicesRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/ChoiceInfoList"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:deleteOldChoices/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /alternative/{choiceID}:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "choiceID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/GetAlternativesResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
        404:
          description: "404 response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:getAlternatives/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        requestTemplates:
          application/json: "$input.params('choiceID')"
        passthroughBehavior: "when_no_templates"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    options:
      consumes:
      - "application/json"
      responses: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
        type: "mock"
  /choice/{choiceID}:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "choiceID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/GetChoiceResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
        404:
          description: "404 response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:getChoice/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        requestTemplates:
          application/json: "$input.params('choiceID')"
        passthroughBehavior: "when_no_templates"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    options:
      consumes:
      - "application/json"
      responses: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
        type: "mock"
  /completeChoice:
    post:
      operationId: "completeChoice"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "CompleteChoiceRequest"
        required: true
        schema:
          $ref: "#/definitions/CompleteChoiceRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/GetChoiceResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
        404:
          description: "404 response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:completeChoice/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /createChoice:
    post:
      operationId: "createChoice"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "CreateChoiceRequest"
        required: true
        schema:
          $ref: "#/definitions/CreateChoiceRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/CreateChoiceResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
        409:
          description: "409 response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:createChoice/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    options:
      consumes:
      - "application/json"
      responses: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
        type: "mock"
  /feedback/{choiceID}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "choiceID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/GetFeedbacksResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
        404:
          description: "404 response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:getFeedbacks/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /feedback/{choiceID}/{participantid}:
    post:
      produces:
      - "application/json"
      parameters:
      - name: "participantid"
        in: "path"
        required: true
        type: "integer"
      - name: "choiceID"
        in: "path"
        required: true
        type: "string"
      
      - name: "PostFeedbackRequest"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/PostFeedbackRequest"
      responses: 
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/GetFeedbacksResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
        404:
          description: "404 response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:postFeedback/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /registerParticipant:
    post:
      operationId: "registerParticipant"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "RegisterParticipantRequest"
        required: true
        schema:
          $ref: "#/definitions/RegisterParticipantRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/RegisterParticipantResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
        404:
          description: "404 response"
        409:
          description: "409 response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:registerParticipant/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    options:
      consumes:
      - "application/json"
      responses: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
        type: "mock"
  /vote/{choiceID}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "choiceID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/GetVotesResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
        404:
          description: "404 response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:getVotes/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /vote/{choiceID}/{participantID}:
    post:
      produces:
      - "application/json"
      parameters:
      - name: "AmendVoteRequest"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/AmendVoteRequest"
          
      - name: "participantID"
        in: "path"
        required: true
        type: "integer"
        
      - name: "choiceID"
        in: "path"
        required: true
        type: "string"
      
      responses: 
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/GetVotesResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
        404:
          description: "404 response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:amendVote/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
definitions:
  AmendVoteRequest:
    type: "object"
    required:
    - "alternativeID"
    - "amendType"
    properties:
      alternativeID:
        type: "integer"
      amendType:
        type: "integer"
        
  VoteInfo:
    type: "object"
    required:
    - "alternativeID"
    - "alternativeName"
    - "numUpvotes"
    - "numDownvotes"
    - "upvoters"
    - "downvoters"
    properties:
      alternativeID:
        type: "integer"
      alternativeName:
        type: "string"
      numUpvotes:
        type: "integer"
      numDownvotes:
        type: "integer"
      upvoters:
        type: "array"
        items: 
          $ref: "#/definitions/StringObject"
      downvoters:
        type: "array"
        items: 
         $ref: "#/definitions/StringObject"
         
  StringObject:
    type: "string"
        
  Alternative:
    type: "object"
    required:
    - "description"
    - "title"
    properties:
      altID:
        type: "integer"
      title:
        type: "string"
      description:
        type: "string"
  RegisterParticipantResponse:
    type: "object"
    required:
    - "statusCode"
    - "response"
    - "participantID"

    properties:
      statusCode:
        type: "integer"
      response:
        type: "string"
      participantID:
        type: "integer"
        
  CreateChoiceRequest:
    type: "object"
    required:
    - "alternativeList"
    - "description"
    - "maxParticipants"
    - "name"
    properties:
      name:
        type: "string"
      maxParticipants:
        type: "string"
      description:
        type: "string"
      alternativeList:
        type: "array"
        items:
          $ref: "#/definitions/Alternative"
  GetFeedbacksResponse:
    type: "object"
    required:
    - "feedbacks"
    - "response"
    - "statusCode"
    properties:
      statusCode:
        type: "integer"
      response:
        type: "string"
      feedbackInfos:
        type: "array"
        items:
          $ref: "#/definitions/FeedbackInfo"
  
  FeedbackInfo:
    type: "object"
    required:
    - "alternativeID"
    - "alternativeName"
    - "numOfFeedbacks"
    - "feedbacks"
    properties:
      alternativeID:
        type: "integer"
      alternativeName:
        type: "string"
      numOfFeedbacks:
        type: "integer"
      feedbacks:
        type: "array"
        items: 
          $ref: "#/definitions/Feedback"
         
  GetVotesResponse:
    type: "object"
    required:
    - "response"
    - "statusCode"
    - "votes"
    properties:
      statusCode:
        type: "integer"
      response:
        type: "string"
      votes:
        type: "array"
        items:
          $ref: "#/definitions/VoteInfo"
  RegisterParticipantRequest:
    type: "object"
    required:
    - "choiceID"
    - "name"
    - "password"
    properties:
      choiceID:
        type: "string"
      name:
        type: "string"
      password:
        type: "string"
  Feedback:
    type: "object"
    required:
    - "participantName"
    - "text"
    properties:
      participantName:
        type: "string"
      text:
        type: "string"
        
  PostFeedbackRequest:
    type: "object"
    required:
    - "alternativeID"
    - "text"
    properties:
      alternativeID:
        type: "integer"
      text:
        type: "string"
        
  DeleteChoicesRequest:
    type: "object"
    required:
    - "howOld"
    properties:
      howOld:
        type: "number"
        
  ChoiceInfo:
    type: "object"
    required:
    - "ID"
    - "dateCompleted"
    - "dateCreated"
    - "isCompleted"
    properties:
      ID:
        type: "string"
      dateCreated:
        type: "object"
        properties: {}
      dateCompleted:
        type: "object"
        properties: {}
      isCompleted:
        type: "boolean"
  CompleteChoiceRequest:
    type: "object"
    required:
    - "choiceID"
    - "participantName"
    - "password"
    properties:
      choiceID:
        type: "string"
      participantName:
        type: "string"
      password:
        type: "string"
        
  GetAlternativesResponse:
    type: "object"
    required:
    - "alternativeList"
    - "response"
    - "statusCode"
    properties:
      statusCode:
        type: "integer"
      response:
        type: "string"
      alternativeList:
        type: "array"
        items:
          $ref: "#/definitions/Alternative"
  ChoiceInfoList:
    type: "object"
    required:
    - "response"
    - "statusCode"
    properties:
      response: 
        type: "string"
      statusCode: 
        type: "integer"
      listOfChoiceInfos:
        type: "array"
        items:
          $ref: "#/definitions/ChoiceInfo"
  CreateChoiceResponse:
    type: "object"
    required:
    - "response"
    - "statusCode"
    properties:
      statusCode:
        type: "integer"
      response:
        type: "string"
  GetChoiceResponse:
    type: "object"
    required:
    - "choice"
    - "response"
    - "statusCode"
    properties:
      statusCode:
        type: "integer"
      response:
        type: "string"
      choice:
        type: "object"
        properties: {}