---
swagger: "2.0"
info:
  description: "cs3733 YAML API"
  version: 1.8.0
  title: "cs3733 YAML API"
host: "65y680psjl.execute-api.us-east-2.amazonaws.com"
basePath: "/beta"
schemes:
- "https"
paths:
  /admin:
    get:
      operationId: "createReport"
      produces:
      - "application/json"
      responses:
        200:
          description: "Report succesfully created"
          schema:
            $ref: "#/definitions/ChoiceInfoList"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "Unable to create report"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:createReport/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    post:
      operationId: "deleteChoices"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "DeleteChoicesRequest"
        required: true
        schema:
          $ref: "#/definitions/DeleteChoicesRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/ChoiceInfoList"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:deleteOldChoices/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /alternative/{choiceID}:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "choiceID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Alternatives succesfully fetched"
          schema:
            $ref: "#/definitions/GetAlternativesResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "Unable to fetch alternatives"
        404: 
          description: "ChoiceID not found"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:getAlternatives/invocations"
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "$input.params('choiceID')"
        passthroughBehavior: "when_no_templates"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /choice/{choiceID}:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "choiceID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Choice succesfully fetched"
          schema:
            $ref: "#/definitions/GetChoiceResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "Unable to fetch choice"
        404:
          description: "ChoiceID not found"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:getChoice/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        requestTemplates:
          application/json: "$input.params('choiceID')"
        passthroughBehavior: "when_no_templates"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
        type: "mock"
  /completeChoice:
    post:
      operationId: "completeChoice"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "CompleteChoiceRequest"
        required: true
        schema:
          $ref: "#/definitions/CompleteChoiceRequest"
      responses:
        200:
          description: "Choice succesfully completed"
          schema:
            $ref: "#/definitions/GetChoiceResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "Choice could not be completed"
        404:
          description: "ChoiceID not found"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:completeChoice/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /createChoice:
    post:
      operationId: "createChoice"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "CreateChoiceRequest"
        required: true
        schema:
          $ref: "#/definitions/CreateChoiceRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/CreateChoiceResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "Unable to create choice"
        409:
          description: "The created ChoiceID conflicts with an existing choice"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:createChoice/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
        type: "mock"
  /feedback:
    post:
      operationId: "postFeedback"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "PostFeedbackRequest"
        required: true
        schema:
          $ref: "#/definitions/PostFeedbackRequest"
      responses:
        200:
          description: "Feedback successfully posted"
          schema:
            $ref: "#/definitions/GetFeedbacksResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "Unable to post feedback"
        404:
          description: "ChoiceID or AlternativeID could not be found"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:postFeedback/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /feedback/{choiceID}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "choiceID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Feedbacks succesfully fetched"
          schema:
            $ref: "#/definitions/GetFeedbacksResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "Feedbacks could not be fetched"
        404:
          description: "ChoiceID could not be found"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:getFeedbacks/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /registerParticipant:
    post:
      operationId: "registerParticipant"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "RegisterParticipantRequest"
        required: true
        schema:
          $ref: "#/definitions/RegisterParticipantRequest"
      responses:
        200:
          description: "Succesfully registered participant"
          schema:
            $ref: "#/definitions/RegisterParticipantResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "Unable to register participant"
        404:
          description: "ChoiceID not found"
        409:
          description: "username already registered with this ChoiceID"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:registerParticipant/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
        type: "mock"
  /vote:
    post:
      operationId: "amendVote"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "AmendVoteRequest"
        required: true
        schema:
          $ref: "#/definitions/AmendVoteRequest"
      responses:
        200:
          description: "Vote succesfully amended"
          schema:
            $ref: "#/definitions/GetVotesResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "Vote could not be amended"
        404:
          description: "ChoiceID or AlternativeID could not be found"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:amendVote/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /vote/{choiceID}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "choiceID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Choices successfully fetched"
          schema:
            $ref: "#/definitions/GetVotesResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "Votes could not be fetched"
        404:
          description: "ChoiceID could not be found"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:375853300759:function:getVotes/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
definitions:
  AmendVoteRequest:
    type: "object"
    required:
    - "amendmentType"
    - "participant"
    - "voteID"
    properties:
      voteID:
        type: "string"
      participant:
        type: "string"
      amendmentType:
        type: "boolean"
  Vote:
    type: "object"
    required:
    - "alternativeID"
    - "participantName"
    - "voteType"
    properties:
      alternativeID:
        type: "string"
      participantName:
        type: "string"
      voteType:
        type: "boolean"
  Alternative:
    type: "object"
    required:
    - "description"
    - "title"
    properties:
      altID:
        type: "string"
      title:
        type: "string"
      description:
        type: "string"
 
  GetChoiceResponse:
    type: "object"
    required:
    - "statusCode"
    - "response"
    - "choice"
    properties:
      statusCode: 
        type: "integer"
      response:
        type: "string"
      choice:
        type: "object"
          
  GetFeedbacksResponse:
    type: "object"
    required:
    - "statusCode"
    - "response"
    - "feedbacks"
    properties:
      statusCode: 
        type: "integer"
      response:
        type: "string"
      feedbacks:
        type: "array"
        items:
          $ref: "#/definitions/Feedback"
    
  RegisterParticipantResponse:
    type: "object"
    required:
    - "response"
    - "statusCode"
    properties:
      statusCode:
        type: "integer"
      response:
        type: "string"

  GetAlternativesResponse:
    type: "object"
    required:
    - "statusCode"
    - "response"
    - "alternativeList"
    properties:
      statusCode:
        type: "integer"
      response:
        type: "string"
      alternativeList:
        type: "array"
        items:
          $ref: "#/definitions/Alternative"
          
  CreateChoiceRequest:
    type: "object"
    required:
    - "alternativeList"
    - "description"
    - "maxParticipants"
    - "name"
    properties:
      name:
        type: "string"
      maxParticipants:
        type: "string"
      description:
        type: "string"
      alternativeList:
        type: "array"
        items:
          $ref: "#/definitions/Alternative"
  PostFeedbackRequest:
    type: "object"
    required:
    - "alternativeID"
    - "name"
    - "text"
    properties:
      alternativeID:
        type: "string"
      name:
        type: "string"
      text:
        type: "string"
  RegisterParticipantRequest:
    type: "object"
    required:
    - "choiceID"
    - "name"
    - "password"
    properties:
      choiceID:
        type: "string"
      name:
        type: "string"
      password:
        type: "string"
  Feedback:
    type: "object"
    required:
    - "alternativeID"
    - "participantName"
    - "text"
    properties:
      alternativeID:
        type: "string"
      participantName:
        type: "string"
      text:
        type: "string"
  DeleteChoicesRequest:
    type: "object"
    required:
    - "howOld"
    properties:
      howOld:
        type: "number"
        
  GetVotesResponse:
    type: "object"
    required:
    - "statusCode"
    - "response"
    - "votes"
    properties:
      statusCode:
        type: "integer"
      response:
        type: "string"
      votes:
        type: "array"
        items:
          $ref: "#/definitions/Vote"
    
  ChoiceInfo:
    type: "object"
    required:
    - "ID"
    - "dateCompleted"
    - "dateCreated"
    - "isCompleted"
    properties:
      ID:
        type: "string"
      dateCreated:
        type: "object"
        properties: {}
      dateCompleted:
        type: "object"
        properties: {}
      isCompleted:
        type: "boolean"
  CompleteChoiceRequest:
    type: "object"
    required:
    - "choiceID"
    - "participantName"
    - "password"
    properties:
      choiceID:
        type: "string"
      participantName:
        type: "string"
      password:
        type: "string"
  ChoiceInfoList:
    type: "object"
    properties:
      listOfChoiceInfos:
        type: "array"
        items:
          $ref: "#/definitions/ChoiceInfo"
  CreateChoiceResponse:
    type: "object"
    required:
    - "response"
    - "statusCode"
    properties:
      statusCode:
        type: "integer"
      response:
        type: "string"